### ISSUE TITLE
TLS IP SAN issues with logstash-forwarder

### ISSUE THREAD

**Issue by nzwulfin** [pires/kubernetes-elk-cluster#2]
I've been seeing an issue that appears to be related to the move to Go 1.3 in logstash-forwarder with non-hostname based SSL certificates.  To use IP addresses, there must be a subject with the appropriate IP,even if ssl strict verify is set to false.

See issues https://github.com/elasticsearch/logstash-forwarder/issues/230 and https://github.com/elasticsearch/logstash-forwarder/issues/221#issuecomment-48390920 for details.

If I'm reading these right, I would need to create the SSL cert for the logstash container after Kubernetes assigns the logstash service an IP address, then make sure the logstash and the logstash-forwarder get the new SSL cert.

**Comment by pires** [comment]
Yes, you're right and thank you for opening this issue because I should have opened it more than a week ago when I spotted this.

You don't need the service IP if you're using [Kubernetes + DNS integration](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/dns.md), which is what I'm using in a tailored version of this repo.

So, not wanting to force a solution on users, I'll be fixing this soon by leaving up to the user the responsibility of providing the certificates.

**Comment by nzwulfin** [comment]
Ah OK, Project Atomic just updated to Kubernetes 0.9.1 so I'll check out setting up a DNS pod with that version.

The cert in the logstash repo doesn't have any CNs at all, did you generate that as a single wildcard or a multi-level, e.g. '_' or '_.*', to match your Kube+DNS setup?

**Comment by pires** [comment]
That certificate does not match what I have in my tailored set-up because I didn't want to force the DNS - or any other - solution.

If you're interested in testing something more up-to-date, check my [Kubernetes cluster made easy with Vagrant](https://github.com/pires/kubernetes-vagrant-coreos-cluster) to Kubernetes 0.11.0. It's CoreOS based, though.

**Comment by pires** [comment]
[`logstash-forwarder`](http://www.elasticsearch.org/guide/en/logstash/roadmap/current/index.html#_logstash_forwarder) releases 0.4.0 and has some good (?) news. I really need to close this.
